
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gtatdbpfopsxkrkgvqiv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0YXRkYnBmb3BzeGtya2d2cWl2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MzI2NDUsImV4cCI6MjA2MDMwODY0NX0.0yv0L-NC5moCSZ2wgsvsP7DepwxNZYTnFhopOArxOdI";

// Define custom database types for our tables
export type TableName = 
  | "modules" 
  | "quiz_questions" 
  | "recommendations" 
  | "user_feedback" 
  | "user_responses" 
  | "user_selections" 
  | "user_settings"
  | "achievements"
  | "community_comments"
  | "community_posts"
  | "profiles"
  | "quiz_completion"
  | "resumes";

export type QuizQuestion = {
  id: number;
  section: "Interest" | "Feasibility" | "Career Goals" | "Learning Style";
  question_text: string;
  question_type: "single-select" | "multi-select" | "text";
  options: string[] | null;
};

export type UserResponse = {
  id: number;
  user_id: string;
  question_id: number;
  response: string | null;
  response_array: string[] | null;
  created_at: string;
};

export type Module = {
  id: number;
  university: "NUS" | "NTU" | "SMU";
  course_code: string;
  title: string;
  aus_cus: number;
  semester: string;
  description: string | null;
};

export type Recommendation = {
  id: number;
  user_id: string;
  module_id: number;
  reason: string;
  created_at: string;
  module?: Module;
  reasoning?: string[];
};

export type UserFeedback = {
  id: number;
  user_id: string;
  module_id: number;
  rating: number;
  created_at: string;
};

export type UserSelection = {
  id: number;
  user_id: string;
  module_id: number;
  created_at: string;
};

export type UserSettings = {
  id: string;
  name: string | null;
  bio: string | null;
  email_notifications: boolean;
  app_notifications: boolean;
  newsletter_subscription: boolean;
  created_at: string;
  updated_at: string;
};

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
